services:
  postgres:
    image: postgres:16-alpine
    container_name: votechain-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: votechain_zero
      POSTGRES_USER: votechain_user
      POSTGRES_PASSWORD: votechain_pass
    ports:
      - "5432:5432"
    volumes:
      - votechain_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U votechain_user -d votechain_zero"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: votechain-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@votechain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    image: maven:3.9-eclipse-temurin-21
    container_name: votechain-app
    working_dir: /app
    command: mvn spring-boot:run
    volumes:
      - .:/app
      - maven_repo_cache:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/votechain_zero
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  votechain_pgdata:
  maven_repo_cache: